server:
  port: 8081

spring:
  profiles:
    active: maria
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://database-1.cemqp9wkhz9q.us-east-1.rds.amazonaws.com:3306/vehicle_register?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

---

spring:
  profiles: maria
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_register?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
